[forest]
host = "liamoc"
trees = ["trees"]   # The directories in which your trees are stored
assets = ["assets"] # The directories in which your assets are stored
theme = "theme"     # The directory in which your theme is stored
url = "https://liamoc.net/forest/"
[renderer]
home = "index"

